[backdrop]
enabled = true

[bar]
order = [ "widgets" ]

    [bar.widgets]
    capsule = true
    capsule_opacity = 0.0
    capsule_padding = 6.0
    center = []
    end = [ "group:g2", "group:g4", "group:g1", "group:g3" ]
    start = [ "launcher", "workspaces", "active_window" ]
    widget_spacing = 8

        [[bar.widgets.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "volume", "bluetooth", "network", "battery", "privacy" ]
        opacity = 0.0
        padding = 6.0

        [[bar.widgets.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "tray" ]
        opacity = 0.0
        padding = 6.0

        [[bar.widgets.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "clock", "notifications" ]
        opacity = 0.0
        padding = 6.0

        [[bar.widgets.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "cpu", "ram" ]
        opacity = 0.0
        padding = 6.0

[battery]
warning_threshold = 15

[calendar]
enabled = true

[config]

[control_center]
sidebar = "full"
sidebar_section = "none"
width = 910

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "nightlight"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
reserve_space = false

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1024.0
    cy = 1161.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 144.0
    box_width = 464.0
    cx = 1024.0
    cy = 328.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 32.0
    box_width = 416.0
    cx = 1024.0
    cy = 240.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        clock_style = "digital"
        color = "on_surface"
        format = "{:%Y/%m/%d (%A)}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 64.0
    box_width = 176.0
    cx = 1920.0
    cy = 80.0
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        shadow = false

[notification]
background_opacity = 0.84999998100101948
border = false

[osd]
background_opacity = 0.84999998100101948
border = false

[plugin_settings."oldirtty/color_picker"]
hyprpicker-lowercase = true

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/notes", "noctalia/translator", "noctalia/wallhaven", "oldirtty/color_picker" ]

[shell]
avatar_path = "/var/lib/AccountsService/icons/yukineko"
date_format = "%x %A"
screen_time_enabled = true
telemetry_enabled = false

    [shell.launcher]
    categories = false
    compact = true

    [shell.panel]
    borders = false
    open_near_click_control_center = true
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 24

    [shell.screenshot]
    confirm_region = true
    directory = "~/Pictures/Screenshots"

    [shell.shadow]
    direction = "center"

[templates]

[theme]
builtin = "Noctalia"
community_palette = "One Dark Two"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "niri", "qt" ]

[wallpaper]
transition = [ "fade" ]

[weather]
effects = false

[widget.active_window]
display = "text_only"
font_weight = 700
max_length = 400

[widget.clock]
font_weight = 700
format = "{:%H:%M:%S}"
tooltip_format = "%x %A"

[widget.cpu]
display = "gauge"
show_label = false

[widget.launcher]
custom_image = "~/nixos-config/assets/logo/nix-snowflake-white.svg"
custom_image_colorize = false

[widget.media]
hide_artist = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.notes]
type = "noctalia/notes:notes"

[widget.notifications]
hide_when_no_unread = true

[widget.privacy]
hide_inactive = true

[widget.ram]
display = "gauge"
show_label = false

[widget.spacer_media]
length = 10
type = "spacer"

[widget.spacer_monitor]
length = 10
type = "spacer"

[widget.spacer_workspace]
length = 10
type = "spacer"

[widget.sysmon]
display = "text"

[widget.volume]
show_label = false

    [widget.volume.actions]
    scroll_down = "none"
    scroll_up = "none"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"
