name: Deno

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Deno
        uses: $/.github/actions/setup-deno

      - name: Type check
        run: deno task check

  shell:
    name: Run cli.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false
          extra-conf: |
            accept-flake-config = true
            tarball-ttl = 31536000

      - name: Restore Nix store cache
        uses: nix-community/cache-nix-action/restore@v7
        with:
          primary-key: nix-cli-${{ runner.os }}-${{ hashFiles('cli.sh') }}
          restore-prefixes-first-match: nix-cli-${{ runner.os }}-
          paths: |
            ~/.cache/nix

      - name: Setup Deno
        uses: $/.github/actions/setup-deno
        with:
          install: false

      - name: Show help
        run: ./cli.sh --help
