name: Deno

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Deno
        uses: $/.github/actions/setup-deno

      - name: Type check
        run: deno task check

  shell:
    name: Run cli.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Nix
        uses: $/.github/actions/setup-nix

      - name: Setup Deno
        uses: $/.github/actions/setup-deno
        with:
          install: false

      - name: Show help
        run: ./cli.sh --help
