name: Create Cache

on:
  push:
    branches: [master]
    paths:
      - cli.sh
      - deno.json
      - deno.lock
      - '**/deno.json'
  workflow_dispatch:

concurrency:
  group: create-cache
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false
          extra-conf: |
            accept-flake-config = true
            tarball-ttl = 31536000

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-cli-${{ runner.os }}-${{ hashFiles('cli.sh') }}
          restore-prefixes-first-match: nix-cli-${{ runner.os }}-
          paths: |
            ~/.cache/nix
          purge: true
          purge-prefixes: nix-cli-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Fetch dependencies
        run: ./cli.sh --help

  deno:
    name: Deno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Deno
        uses: $/.github/actions/setup-deno
