name: Create Cache

on:
  push:
    branches: [master]
    paths:
      - cli.sh
      - deno.json
      - deno.lock
      - '**/deno.json'
  workflow_dispatch:

concurrency:
  group: create-cache
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Nix
        uses: $/.github/actions/setup-nix
        with:
          purge: true

      - name: Fetch dependencies
        run: ./cli.sh --help

  deno:
    name: Deno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Deno
        uses: $/.github/actions/setup-deno
